# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/python:3.12

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-{{ .Branch }}-

      - run:
          name: install dependencies
          command: |
            pip install pipenv
            pipenv sync --dev

      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ./venv
            - /usr/local/bin

      - run:
          name: run code checks
          command: |
            make check


      - run:
          name: run tests
          command: |
            make coverage

      - store_artifacts:
          path: test-reports
          destination: test-reports